try{
    let a;
    console.log(a.length);
    console.log("hi from inside try")
}catch(e){
    console.log("inside catch");
}

console.log("hi from outside")